source 'https://rubygems.org'

# gem 'rubocop'
gem 'aws-sdk'
gem 'fog-aws'
gem 'rake'
gem 'rubocop', require: false
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
# Specify your gem's dependencies in second.gemspec
gemspec
